version: '3'
services:
  app:
    # In development, use the following instead of the ECR image.
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: publics-digest-api:macos2.0
    ports:
      - "3000:3000"
    restart: always
    # environment:
    #   - DATABASE_URL=postgresql://flavius:password@postgresql:5432/digest?schema=public
    depends_on:
      - postgres

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=flavius
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
